# Generated by Django 5.2 on 2025-07-13 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Débito/Crédito'), ('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia Bancaria'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Número de referencia para pagos electrónicos', max_length=100, null=True, verbose_name='Referencia del Pago'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='autorizada',
            field=models.BooleanField(default=False, verbose_name='Venta Autorizada'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='autorizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_autorizadas', to='black_invoices.empleado', verbose_name='Autorizada por'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='comentarios_autorizacion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de Autorización'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='requiere_autorizacion',
            field=models.BooleanField(default=True, verbose_name='Requiere Autorización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Describe las características del producto', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio en dólares (Máximo: $5,000.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio no puede ser menor a $0.01'), django.core.validators.MaxValueValidator(5000.0, message='El precio no puede ser mayor a $5,000.00')], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible (Máximo: 100,000 unidades)', validators=[django.core.validators.MaxValueValidator(100000, message='El stock no puede ser mayor a 100,000 unidades')], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
