# Generated by Django 5.1.5 on 2025-03-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='monto_comision',
            new_name='monto_venta',
        ),
    ]
