# Generated by Django 5.2 on 2025-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodo_pag',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
