# Generated by Django 5.2 on 2025-04-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0002_rename_monto_comision_comision_monto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='monto_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de venta'),
        ),
    ]
