# Generated by Django 5.2 on 2025-04-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0003_alter_comision_monto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='credito',
            field=models.BooleanField(default=False, verbose_name='Venta a Crédito'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado'),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='black_invoices.ventas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
